name: anime_cast
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  http: ^1.1.0
  mockito: ^5.4.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
